### ISSUE TITLE
Support option for `supportsAllDrives`

### ISSUE THREAD

**Issue by sr-pakwai** [hankei6km/guratan#126]
Hi,

For context, I am currently using this (https://github.com/hankei6km/gdrive-act-send) shared action as part of my workflow. And was hitting an error similar to this in my Github action workflow.
https://stackoverflow.com/questions/64649976/google-service-account-permissions-file-not-found-error

It seems that the solution to this is to allow `supportsAllDrives`. The original repo of the implementation leads to this repo. Thus, decided to create the issue here.

Anyway, the problem is highlighted in the title already. And, it seems to be a common issue discussed in other Github repo
https://github.com/search?q=supportsAllDrives&type=issues

**Comment by hankei6km** [comment]
Hi,

Added `supportsAllDrives` option to this package. But unfortunately I don't have a shared drive for testing.

I have released latest `gdrive-act-send` as `0.6.0` which links the new package, so could you try it?

https://github.com/marketplace/actions/google-drive-tools-action-send

| parameter | description | required | default |
| --- | --- | --- | --- |
| supports_all_drives | Supports both My Drives and shared drives(`includeItemsFromAllDrives` is also enabled) | `false` |  |

**Comment by sr-pakwai** [comment]
Tested, and is working. Thanks for the feature request. :)

**Comment by hankei6km** [comment]
@sr-pakwai Thank you for trying.

I'm glad to be able to add this new feature.
